### ISSUE TITLE
Error when executing commands in console

### ISSUE THREAD

**Issue by Andre601** [ArtFect/BlockHighlight#1]
You receive this exception when executing the command in console using PaperMC:

```
> bh stop
[23:30:47 WARN]: Unexpected exception while parsing console command "bh stop"
org.bukkit.command.CommandException: Unhandled exception executing command 'bh' in plugin BlockHighlight v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-584]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-584]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-584]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:452) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-584]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader 'app')
        at ru.fiw.blockhighlight.BHCommand.onCommand(BHCommand.java:66) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-584]
        ... 9 more
```

Used on PaperMC 1.16.5 (Build 584)

Additionally does the plugin spam `No animation with name test was found!` in console by default.

**Comment by ArtFect** [comment]
Fixed error with bh stop

Are you sure plugin spam this by default?
Maybe you changed the name of the first animation or deleted it, but did not delete the repetition

**Comment by Andre601** [comment]
> Fixed error with bh stop
> 
> Are you sure plugin spam this by default?
> Maybe you changed the name of the first animation or deleted it, but did not delete the repetition

It does happen by default with the default configuration and everything.
