### ISSUE TITLE
Plugin spams console when players are not in the same world

### ISSUE THREAD

**Issue by Andre601** [ArtFect/BlockHighlight#3]
I seriously have to ask: Was this plugin even tested at all?

This error appears when (I assume) a player is or was last seen in a world other than the one where the animation is located at

```
[22:48:43 WARN]: [BlockHighlight] Task #533 for BlockHighlight v1.0 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between spawn_nether and spawn
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.5.jar:git-Paper-584]
        at ru.fiw.blockhighlight.RunningAnimation.render(RunningAnimation.java:24) ~[?:?]
        at ru.fiw.blockhighlight.Main$1.run(Main.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-584]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1413) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-584]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by ArtFect** [comment]
It depends on what you mean by testing - the main functionality of course was tested during creation. There was no complete comprehensive testing to identify ALL the bugs. Because the point of the plugin is to show a new feature, and not to create a perfect plugin for an existing one

Fixed 
https://www.spigotmc.org/resources/blockhighlight.91087/update?update=398138
